import React from 'react'
import Header from '../components/header'
import Footer from '../components/footer'
const contact = () => {
  return (
    <div>
        <Header/>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi architecto, in id commodi similique veniam voluptates molestias quas natus tenetur aliquid possimus adipisci quod eaque repudiandae dolores fugiat sunt rerum! Nam incidunt saepe omnis non nulla ut velit eaque corporis voluptate perspiciatis ullam quaerat quod, sed similique voluptatum vel. Eligendi assumenda earum quaerat et neque amet cum, laudantium pariatur. Suscipit ut ducimus iusto. Suscipit pariatur exercitationem corporis! Assumenda voluptatem, natus modi deserunt explicabo quod hic. Voluptate tempora quod alias, veritatis temporibus tenetur dolore. Tempore necessitatibus eum, pariatur culpa et delectus officiis iure quia mollitia distinctio magnam doloribus ut, eius dolorem quasi nostrum consectetur provident a rerum esse quibusdam, quod quidem ea. Quos facere beatae dolores fugit doloribus. Officiis non eaque aliquam, minus ea aut magnam totam alias recusandae. Praesentium molestias quod et, quidem quam dolorum natus cupiditate? Necessitatibus laborum, deleniti quaerat consequuntur reiciendis sapiente in facilis voluptate ipsam nihil minus magni suscipit tempore doloribus alias magnam tempora repudiandae eum, veniam incidunt. Enim, voluptas ut sed necessitatibus vero, at impedit quae id quibusdam soluta tenetur, ex rerum explicabo laboriosam illum assumenda possimus sapiente beatae obcaecati a dolorum quia sit. Quibusdam ut fuga dignissimos maxime repudiandae itaque perferendis accusantium voluptates, excepturi eaque suscipit, praesentium sequi nobis soluta adipisci at deserunt aliquam doloribus. Magnam, ratione fuga impedit ea libero tenetur sapiente repudiandae magni esse non repellendus ipsum, ipsam, possimus omnis molestias placeat laudantium! Quam ipsa et autem alias dolor dolorem, quo, eveniet explicabo incidunt commodi, odio doloremque. Sequi ducimus placeat, quis quia dolorem explicabo blanditiis accusamus illum omnis iste sit rem repellendus labore, animi, cum doloribus illo maiores praesentium dolorum ullam facere impedit asperiores? Earum ipsam similique aspernatur iure, ducimus autem odio cum debitis? Quae optio ea ipsa nostrum quod eum aut fugit iste quis. Itaque, error id recusandae, vitae aliquam adipisci officiis earum inventore nostrum fugit, obcaecati ab qui quibusdam ratione? Magni dolores itaque saepe dolorem sapiente voluptates at dicta suscipit maxime quas fugit iusto dolore beatae obcaecati repudiandae consectetur magnam soluta, amet quam quibusdam explicabo odio, eius quis. Blanditiis quibusdam harum magni nisi, quod commodi consectetur dolore deleniti aperiam impedit nesciunt quis ipsum, atque facilis recusandae quidem non neque quos exercitationem sit quae? Dolores maiores repellendus esse voluptates quas odio aperiam ipsum at consectetur unde veritatis, neque excepturi fugit fuga exercitationem ab. Expedita aliquam repellat officiis ipsum nisi? Sequi, illum. Optio debitis itaque saepe atque obcaecati distinctio, ab repellat animi sit!</p>
      <Footer/>
    </div>
  )
}

export default contact
